### ISSUE TITLE
Error returned from UDT when re-downloading already downloaded manifest

### ISSUE THREAD

**Issue by BedfordWest** [millerjs/parcel#45]
I successfully downloaded all files from a manifest successfully over UDT in the QA environment using my staging token, but when I tried to execute the same parcel command ( parcel udt https://parcel.service.consul/data -m gdc_manifest_c1c4d8fcb03b0e26be2c3a98a5a2cc4f8288ec4b.txt -d parceldownload -n1 -t stagingtoken ), I received the following error:

Process Process-42:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/parcel/src/parcel/parcel/client.py", line 20, in download_worker
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 304, in SocketClient
    s.connect(address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory

Attached is a screenshot of the manifest file I was using to download.
![screen shot 2015-05-01 at 2 04 33 pm](https://cloud.githubusercontent.com/assets/2050190/7435650/0553aeee-f00b-11e4-8084-69089af7d29b.png)

**Comment by BedfordWest** [comment]
Additional info: 
I tried the same download again, and while most of the downloads immediately said the file had been fully downloaded, some seemed to instantly re-download. I also received an error at the end again, but this time it was different:

Process Process-42:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/parcel/src/parcel/parcel/client.py", line 20, in download_worker
    interval = producer.q_work.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 755, in _callmethod
    self._connect()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 742, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 175, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python2.7/multiprocessing/connection.py", line 428, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
EOFError

**Comment by BedfordWest** [comment]
I tried a third time and it completely successfully with no errors.
The fourth time, Parcel completely hung after a "File already complete." message, and remained hung for about an hour before I finally killed it manually.
